-- MySQL Script generated by MySQL Workbench
-- Wed Oct  3 11:38:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema railwayticketbokapp1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `railwayticketbokapp1` ;

-- -----------------------------------------------------
-- Schema railwayticketbokapp1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railwayticketbokapp1` DEFAULT CHARACTER SET utf8 ;
USE `railwayticketbokapp1` ;

-- -----------------------------------------------------
-- Table `railwayticketbokapp1`.`trains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railwayticketbokapp1`.`trains` ;

CREATE TABLE IF NOT EXISTS `railwayticketbokapp1`.`trains` (
  `id` INT NOT NULL,
  `trainname` VARCHAR(45) NULL,
  `class3seats` VARCHAR(45) NULL,
  `class2seats` VARCHAR(45) NULL,
  `class1seats` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railwayticketbokapp1`.`timetable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railwayticketbokapp1`.`timetable` ;

CREATE TABLE IF NOT EXISTS `railwayticketbokapp1`.`timetable` (
  `id` INT NOT NULL,
  `trainid` INT NULL,
  `startsat` VARCHAR(65) NULL,
  `destination` VARCHAR(65) NULL,
  `starttime` VARCHAR(65) NULL,
  `endtime` VARCHAR(45) NULL,
  `trainclass` INT NULL,
  `price` DECIMAL NULL,
  `createdat` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `trainForignKey_idx` (`trainid` ASC),
  CONSTRAINT `trainForignKey`
    FOREIGN KEY (`trainid`)
    REFERENCES `railwayticketbokapp1`.`trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railwayticketbokapp1`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railwayticketbokapp1`.`ticket` ;

CREATE TABLE IF NOT EXISTS `railwayticketbokapp1`.`ticket` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `nic` VARCHAR(15) NULL,
  `traintimeid` INT NULL,
  `count` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `traintimeForginKey_idx` (`traintimeid` ASC),
  CONSTRAINT `traintimeForginKey`
    FOREIGN KEY (`traintimeid`)
    REFERENCES `railwayticketbokapp1`.`timetable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
